### ISSUE TITLE
recommendations about bots vs components

### ISSUE THREAD

**Issue by flosse** [xmpp-iot/xmpp-iot.github.io#7]
Are there any best practices for xmmp-iot device implementations?
In which case would you use components and when does it make sense to implement bots?

**Comment by joachimlindborg** [comment]
Well an XMPP-IoT device is really just a device that sits some where in the world and does it job. really just a client(bot) I would say. It won't manage several JIDs. Components are bigger and should really reside somewhere near the server (Security). They could be used to encapsulate some kind of legacy system where you would model several JID's. Perhaps device1235@proprietarythings.example.com.

**Comment by flosse** [comment]
> Components [...] could be used to encapsulate some kind of legacy system where you would model several JID's. Perhaps device1235@proprietarythings.example.com.

I see.
So e.g. a electrical laboratory with some IoT devices would be modeled as a bot (e.g.  lab1@example.org and within that laboratory there is a component that represents devices (e.g. device12345@lab-component.local.domain)?
Let's say there are 20 devices that all talk via a proprietary tcp protocol. Then it might be better to use only one component that talks to them instead of starting 20 bots, right?

Maybe we could add a section to the xmm-iot site that helps with some of these modelling questions in general?. In that laboratory case it would be a subsection like _"modeling a local/private IoT-domain with an public concentrator"_.

**Comment by joachimlindborg** [comment]
Yes having one component providing several JID's to hide a proprietary protocol can be very good. I would only see a problem if the proprietary protocol management leads to a massive multithreaded component. Running it as bots the bots can be running anywhere. The component would probably run on the xmpp server. 

Yes a modelling post could be very useful you can do one under the http://xmpp-iot.org/basics/ there is one with the basic model of a device with nodes and fields please read and refine if you don't understand
